accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Define URL patterns for blogs."""
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows a specific blog.
    path('blog/blog_id=<int:blog_id>/', views.blog, name='blog'),
    # Page to add a new blog.
    path('new_blog', views.new_blog, name='new_blog'),
    # Page to add a new blog post.
    path('new_blogpost/blog_id=<int:blog_id>/', views.new_blogpost, name='new_blogpost'),
    # Page to edit existing blog name.
    path('edit_blogname/blog_id=<int:blog_id>/', views.edit_blogname, name='edit_blogname'),
    # Page to edit existing blogpost.
    path('edit_blogpost/blog_post_id=<int:blog_post_id>/', views.edit_blogpost, name='edit_blogpost'),
    # Page to show user's blogs and blog posts.
    path('my_blogs', views.my_blogs, name='my_blogs'),
    # Admin page that shows all unpublished blogs.
    path('review_blog', views.review_blog, name='review_blog'),
    # # Admin page to confirm publishing of a blog.
    path('publish_blog/blog_id=<int:blog_id>', views.publish_blog, name='publish_blog'),
    # Admin page that shows all unpublished blog posts.
    path('review_blogposts', views.review_blogposts, name='review_blogposts'),
    # Admin page to confirm publishing of a blog post.
    path('publish_blogpost/blog_post_id=<int:blog_post_id>/', views.publish_blog_post, name='publish_blog_post'),
    # Admin page to delete a blog topic and all associated posts.
    path('delete_blog/blog_id=<int:blog_id>', views.delete_blog, name='delete_blog'),
    # Page to delete specified blog post.
    path('delete_post/blog_post_id=<int:blog_post_id>', views.delete_post, name='delete_post'),
    ]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    """The model for a blog."""
    text = models.CharField(max_length=43)
    date_made = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class BlogPost(models.Model):
    """The specific post for a blog."""
    blog_to_post_under = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
    title = models.CharField(null=True, max_length=64) # Post title
    text = models.TextField(null=True) # Post entry
    date_made = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Blog Posts'
    
    def __str__(self):
        return str(self.title)

blogs/forms.py
from django import forms

from .models import Blog, BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['text']
        labels = {'text': ''}


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['blog_to_post_under', 'title', 'text',]
        labels = {'blog_to_post_under': 'Post Under:', 'title': 'Title', 'text': ''}
        widgets = {
            'text': forms.Textarea(attrs={'cols': 80, 'rows': 40}),
            }

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test

from .functions import check_admin, check_blog_owner, check_if_live
from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm
# Create your views here.

def index(request):
    """Home page for Blogs. Public Blog Topics will appear here."""
    # Set alphabetical order of the blog titles
    blog_titles = Blog.objects.order_by('text')
    context = {'blog_titles': blog_titles}
    return render(request, 'blogs/index.html', context)

# Send non-superusers to home page if trying to access review_blog.
# login_url="/" is the syntax to redirect to homepage instead of login page.
@user_passes_test(check_admin, login_url="/", redirect_field_name=None)
def review_blog(request):
    """Admin only page. This shows all blogs that aren't
    published yet."""
    blogs = Blog.objects.filter(public=False)
    context = {'blogs': blogs}
    return render(request, 'blogs/review_blog.html', context)

@user_passes_test(check_admin, login_url="/", redirect_field_name=None)
def review_blogposts(request):
    """Admin only page. This shows all blogposts that aren't published yet."""
    blog_posts = BlogPost.objects.filter(public=False)
    context = {'blog_posts': blog_posts}
    return render(request, 'blogs/review_blogposts.html', context)

@user_passes_test(check_admin, login_url="/", redirect_field_name=None)
def publish_blog(request, blog_id):
    """Admin only page. This page confirms the publishing of a blog."""
    blog = Blog.objects.get(id=blog_id)
    blog.public = True
    blog.save()
    context = {'blog': blog}
    return render(request, 'blogs/publish_blog.html', context)

@user_passes_test(check_admin, login_url="/", redirect_field_name=None)
def publish_blog_post(request, blog_post_id):
    """Admin only page. This page confirms the publishing of a blog post."""
    bp = BlogPost.objects.get(id=blog_post_id)
    blog = bp.blog_to_post_under # Retrieve associated blog for redirect.
    bp.public = True
    bp.save()
    context = {'bp': bp, 'blog': blog}
    return render(request, 'blogs/publish_blog_post.html', context)

def blog(request, blog_id):
    """The page to display a specific blog and its posts."""
    blog = Blog.objects.get(id=blog_id)
    check_if_live(blog) # Raise 404 if blog isn't live.
    blog_posts = blog.blogpost_set.order_by('-date_made')
    context = {'blog': blog, 'blog_posts': blog_posts}
    return render(request, 'blogs/blog.html', context)

@user_passes_test(check_admin, login_url="/", redirect_field_name=None)
def new_blog(request):
    """Admin only page. Add a new blog topic."""
    if request.method != 'POST':
        # No data submitted; create blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:review_blog')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def new_blogpost(request, blog_id):
    """Add a new blog post under specified blog_id."""
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        # No data submitted; create blank form with curent blog initially in the dropdown.
        form = BlogPostForm(initial={"blog_to_post_under": blog})
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_blogpost = form.save(commit=False)
            new_blogpost.blog = blog
            new_blogpost.owner = request.user
            new_blogpost.save()
            return redirect('blogs:my_blogs')
    
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_blogpost.html', context)

@user_passes_test(check_admin, login_url="/", redirect_field_name=None)
def edit_blogname(request, blog_id):
    """Admin only. Edit an existing blog name."""
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        # Initial request; pre-fill form with current entry.
        form = BlogForm(instance=blog)
    else:
        # POST data submitted; process data.
        form = BlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blogname.html', context)

@login_required
def edit_blogpost(request, blog_post_id):
    """Edit an existing blog post."""
    blogpost = BlogPost.objects.get(id=blog_post_id)
    blog = blogpost.blog_to_post_under
    # If request user does not match blog owner, raise 404 exception.
    check_blog_owner(blogpost, request.user)

    if request.method != 'POST':
        # Initial request; pre-fill form with current entry.
        form = BlogPostForm(instance=blogpost)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            edited_bp = form.save(commit=False)
            edited_bp.public = False
            edited_bp.save()
            return redirect('blogs:my_blogs')
        
    context = {'blogpost': blogpost, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blogpost.html', context)

@login_required
def my_blogs(request):
    """
    Page to show current user's blogs and blog posts, whether they are published
    or not.
    """
    blogs = Blog.objects.order_by("text")
    blog_posts = BlogPost.objects.order_by("blog_to_post_under")
    user = request.user
    context = {'blogs': blogs, 'blog_posts': blog_posts, 'user': user}
    return render(request, 'blogs/my_blogs.html', context)

@user_passes_test(check_admin, login_url="/", redirect_field_name=None)
def delete_blog(request, blog_id):
    """Page to delete a specific blog and all associated posts."""
    blog = Blog.objects.get(id=blog_id)

    if request.method == 'POST':
        blog.delete()
        return redirect('/') # Go back to home page once blog deleted.
    
    context = {'blog': blog}
    
    return render(request, 'blogs/delete_blog.html', context)


def delete_post(request, blog_post_id):
    """Page for current user to delete their specific blog post."""
    post = BlogPost.objects.get(id=blog_post_id)
    blog = post.blog_to_post_under # Retrieve associated blog for redirect.
    check_blog_owner(post, request.user)

    if request.method == 'POST':
        post.delete()
        return redirect('blogs:blog', blog_id=blog.id)
    
    context = {'post': post}

    return render(request, 'blogs/delete_post.html', context)

blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>The Classic Blog App</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blogs:index' %}">
        Classic Blog</a>
    
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          {% if user.is_authenticated %}
            {% if user.is_superuser == True %}
              <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:new_blog' %}">
                Create a New Blog</a></li>
            {% endif %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:my_blogs' %}">
                View My Blogs</a></li>
            {% if user.is_superuser == True %}
                <li class ="nav-item">
                <a class="nav-link" href="{% url 'blogs:review_blog' %}">
                    Review Blogs</a></li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'blogs:review_blogposts' %}">
                    Review Blog Posts</a></li>
            {% endif %}
          {% endif %}
        </ul> <!-- End of links on left sidebar -->
    
      <!-- Start of account-related links on right side -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hi, {{ user.username }}!
              </span>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                Log in</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                Register</a></li>
          {% endif %}
        </ul> <!-- End of account-related links -->

      {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <button name="submit" class="btn btn-outline-secondary btn-sm">
            Log out</button>
        </form>
      {% endif %}
      </div> <!-- Closes collapsible parts of navbar -->
    </div> <!-- Closes navbar container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <!-- Start of Page Header Section -->
    <div class="pb-2 mb-4 border-bottom">
      {% block page_header %}{% endblock page_header %}    
    </div>
    <!-- End of Page Header Section -->
    
    <!-- Start of Page Body Section -->
    <div>
      {% block content %}{% endblock content %}
    </div>
    <!-- End of Page Body Section -->
  </main>

</body>
</html>

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block page_header %}
<h2>Blog Posts: {{ blog.text }}</h2>
{% endblock page_header %}

{% block content %}
  {% if user.is_authenticated %}
    <a href="{% url 'blogs:new_blogpost' blog.id %}"
      class="btn btn-primary btn-sm mt-1 mb-4">Add New Blog Post for {{ blog.text }}</a>
  {% endif %}
  
  {% for bp in blog_posts %}
    {% if bp.public == True %}
      <div class="card mb-3">
        <h5 class="card-header d-flex">
          {{ bp.title }}
            {% if request.user == bp.owner %}
              <span class="ms-auto text-muted">
                <div class="user-action-buttons">
                  <a href="{% url 'blogs:edit_blogpost' bp.id %}" class="btn btn-warning btn-sm">Edit Blog Post</a>
                  <a href="{% url 'blogs:delete_post' bp.id %}" class="btn btn-danger btn-sm">Delete Blog Post</a>
                </div>
              </span>
            {% endif %}
        </h5>
        <div class="card-body">{{ bp.text|linebreaks }}</div>
          <div class="card-footer">
            <p class="card-text text-muted">
              <small>
                Author: {{ bp.owner }} | Last Updated: {{ bp.date_updated|date:'M d, Y H:i' }}
              </small>
            </p>
          </div>
        </div>
    {% else %}
    {% endif %}
      </div>
  {% empty %}
    <p>There are no blog posts yet for {{ blog.text }}.</p>
  {% endfor %}


{% endblock content %}

blogs/templates/blogs/delete_blog.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Delete {{ blog }}?</h2>
{% endblock page_header %}

{% block content %}
<div class="text-danger">
    <p><strong>NOTE! All posts associated with this blog will be 
      removed! This action cannot be undone.</strong>
    </p>
</div>
<form action="{% url 'blogs:delete_blog' blog.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_button button_type="submit" content="Delete Blog" %}
</form>

{% endblock content %}

blogs/templates/blogs/delete_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Delete {{ post.title }}?</h2>
{% endblock page_header %}

{% block content %}
<div class="text-danger">
    <p><strong>NOTE! This action cannot be undone.</strong></p>
</div>
<form action="{% url 'blogs:delete_post' post.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_button button_type="submit" content="Delete Post" %}
</form>

{% endblock content %}

blogs/templates/blogs/edit_blogname.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Edit Blog Name</h2>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:edit_blogname' blog.id %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="Edit Blog Name" %}
  
</form>
{% endblock content %}

blogs/templates/blogs/edit_blogpost.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}


{% block page_header %}
<h2>Edit Blog Post</h2>
{% endblock page_header %}

{% block content %}
<p>Return to <a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>
<div class="text-danger">
  <p><strong>NOTE! Your edits will be reviewed before the updated post is published.</strong></p>
</div>

<form action="{% url 'blogs:edit_blogpost' blogpost.id  %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="Edit Blog Post" %}
</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <div class="p-3 mb-3 bg-light border rounded-4">
    <div class="container-fluid py-4">
      <h1 class="display-3">Blog about everything you care about.</h1>
      
      <p class="lead">Create blogs and share it with the world! Add or edit blog posts,
        and read other user's blog posts.</p>
      <!-- Show Register CTA if user not logged in. -->
      {% if user.is_authenticated %}
      {% else %}
        <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'accounts:register' %}">Register &raquo;</a>
      {% endif %}
    </div>
  </div>
{% endblock page_header %}

{% block content %}
<div class="row card-deck d-flex">
  <h2>Published Blogs</h2>
  {% for blog_title in blog_titles %}
    {% if blog_title.public == True %}
      <div class="col-sm-4">
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">{{ blog_title.text }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Created by: {{ blog_title.owner }}
              on {{blog_title.date_made|date:'M d, Y'}}
            </h6>
            <a href="{% url 'blogs:blog' blog_title.id %}" class="btn btn-primary btn-sm">See Blog Posts</a>
            <!-- Show Edit Blog Name and Delete Blog buttons if superuser. -->
            {% if user.is_superuser == True %}
              <a href="{% url 'blogs:edit_blogname' blog_title.id %}" class="btn btn-primary btn-sm">Edit Blog Name</a>
              <a href="{% url 'blogs:delete_blog' blog_title.id %}" class="btn btn-danger btn-sm">Delete Blog</a>
            {% endif %}
          </div>
        </div>
    {% endif %}
      </div>
  {% empty %}
    <p>There are no active blogs yet.</p>
  {% endfor %}
</div>
{% endblock content %}

blogs/templates/blogs/my_blogs.html
{% extends "blogs/base.html" %}

{% block page_header %}
<h2>My Blogs</h2>
{% endblock page_header %}

{% block content %}
  {% for blog in blogs %}
    {% for bp in blog_posts %}
      {% if bp.blog_to_post_under == blog %}
        {% if request.user == bp.owner %}
          <div class="card mb-3">
            <div class="card-header d-flex"><h5>Blog Post: {{ bp.title }}</h5>
              <span class="ms-auto text-muted">
                <div class="user-action-buttons">
                  <a href="{% url 'blogs:edit_blogpost' bp.id %}" class="btn btn-warning btn-sm">Edit Blog Post</a>
                  <a href="{% url 'blogs:delete_post' bp.id %}" class="btn btn-danger btn-sm">Delete Blog Post</a>
                </div>
              </span>
            </div>
            <div class="card-body">
              {{ bp.text|linebreaks }}
            </div>
            <div class="card-footer d-flex">
              <small>Under Blog:
                <a href="{% url 'blogs:blog' blog.id%}"
                  class="btn btn-primary btn-sm">{{ blog.text }}</a>
              </small>
              <p class="card-text text-muted ms-auto">
                <small>
                Date Created: {{ bp.date_made|date:'M d, Y H:i' }}
                </small>
              </p>
              {% if bp.public == False %}
                {% if user.is_superuser == True%}
                  <span class="ms-auto"><a href="{% url 'blogs:publish_blog_post' bp.id %}" 
                    class="btn btn-success btn-sm">Push Live</a></span>
                {% else %}
                  <span class="ms-auto text-muted"><small>This post is under review.</small></span>  
                {% endif %}
              {% else %}
              <span class="ms-auto text-success"><small><strong>This post is live!</strong></small>
              </span>  
              {% endif %}
            </div>
        {% endif %}
      {% endif %}  
          </div>
    {% endfor %}
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Add a new blog</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'blogs:new_blog' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add new blog" %}
  </form>
<br>
<div class="p-1 text-danger">
  <p class="fw">NOTE! Your blog will not be published until it is pushed live
    on the "Review Blogs" page.
  </p>
  </div>
{% endblock content %}

blogs/templates/blogs/new_blogpost.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Add New Post for Blog: {{ blog.text }}</h2>
{% endblock page_header %}

{% block content %}
<div class="text-primary">
    <p><strong>Your post will be reviewed before it is published. You can view
      the status of your post in "View My Blogs".
    </strong>
    </p>
</div>
<form action="{% url 'blogs:new_blogpost' blog.id %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="Add New Blog Post" %}
</form>
{% endblock content %}

blogs/templates/blogs/publish_blog.html
{% extends 'blogs/base.html' %}

{% block page_header %}
<h2>{{ blog.text }} has been published!</h2>
{% endblock page_header %}

{% block content %}
<a href="{% url 'blogs:index' %}"
class="btn btn-primary btn-sm mt-1">Return Home</a>
{% endblock content %}

blogs/templates/blogs/publish_blog_post.html
{% extends 'blogs/base.html' %}

{% block page_header %}
<h2>{{ bp.title }} has been published!</h2>
{% endblock page_header %}

{% block content %}
<a href="{% url 'blogs:blog' blog.id %}"
class="btn btn-primary btn-sm mt-1">Return to {{ blog }}</a>
{% endblock content %}

blogs/templates/blogs/review_blog.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h2>Review Blogs</h2>
{% endblock page_header %}

{% block content %}
<p><strong>The following blogs are ready to be published on the website:</strong></p>

<ul class="list-group border-bottom pb-2 mb-4">
    {% for blog in blogs %}
      <li class="list-group-item border-0">
        {{ blog.text }}
        <a href="{% url 'blogs:publish_blog' blog.id %}"
          class="btn btn-success btn-sm">Push Live</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">No blogs to review.</li>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/review_blogposts.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h2>Review Blog Posts</h2>
{% endblock page_header %}

{% block content %}
<p><strong>The following blog posts are ready to be published:</strong></p>

{% for bp in blog_posts %}
  <div class="card mb-3">
    <h5 class="card-header">
      {{ bp.title }}
        <a href="{% url 'blogs:publish_blog_post' bp.id %}"
          class="btn btn-success btn-sm">Push Live</a>
    <div class="card-subtitle">
      <sub>This Blog Post will be published under: {{ bp.blog_to_post_under }}</sub>
    </div>
    </h5>
    <div class="card-body">{{ bp.text|linebreaks }}</div>
      <div class="card-footer">
        <p class="card-text text-muted">
          <small>
            Author: {{ bp.owner }} | Last Updated: {{ bp.date_updated|date:'M d, Y H:i' }}
          </small>
        </p>
      </div>
    </div>
</div>
{% empty %}
<p>There are no blog posts to review!</p>
{% endfor %}

{% endblock content %}